### ISSUE TITLE
errors should tell who to contact when it happens

### ISSUE THREAD

**Issue by benoitc** [erlef/website#252]
When an error happen on the website we should let people know who to contact/where to open a ticket when it happens. This would simplify the maintenance and possibly allows anyone working on the infra  to eventually answer to it.

**Comment by starbelly** [comment]
Yes I agree. When an unhandled error happens as of now it simply gets converted to a 500 and we spit out "Internal server error" which is not helpful at all.

**Comment by starbelly** [comment]
This has been resolved via dab86ab74727ffb388df6708010168e2d2c2ce6c 

Simple 500 page : 
<img width="601" alt="Screen Shot 2021-02-03 at 12 14 55 AM" src="https://user-images.githubusercontent.com/39971740/106706152-da8b1a00-65b4-11eb-9e6e-dd3d063656ff.png">

And added a simple 404 page:
<img width="595" alt="Screen Shot 2021-02-03 at 12 15 26 AM" src="https://user-images.githubusercontent.com/39971740/106706198-ec6cbd00-65b4-11eb-985e-665568e92667.png">


We may want to adjust the contact information or perhaps link to a template instead of the main page of the repo, but let's open another ticket for that 😁
