### ISSUE TITLE
Ex11 - Joe's paper on GUI in concurrent programming langauge

### ISSUE THREAD

**Issue by bcardarella** [erlef/website#96]
https://dl.acm.org/citation.cfm?doid=1022471.1022472

Are ACM articles ok? It's behind their walled garden. If not there is a presentation style version of this paper out there:

http://erlang.se/workshop/2004/ex11.pdf

**Comment by pdgonzalez872** [comment]
@bcardarella! Thanks for looking into this!

That's a good point. I ran into this issue with one of the papers someone sent me. At that time, there was another link to it so I used that instead. Seems like it is time to discuss these paywalled/walled papers.

In my opinion, if just a wall (not paid) we should include it. I'm not too sure about paywalls though. I'd vote no on them at the moment.

As far as the presentation linked here, I would vote to not include it. It feels that it is missing a lot of context without the paper to go with it.

Thanks for looking into this!

cc: @starbelly @miriampena @adolfont what are your thoughts on this?

**Comment by adolfont** [comment]
Well, using SciHub or [Unpaywall](https://twitter.com/unpaywall) anyone can have access to most ACM papers.

I had to add that ["We most definitely should never encourage the use of Sci-Hub. That thing called Sci-Hub should not be endorsed by any academic. We should just keep repeating Sci-Hub so people know that they should not use it to get paywalled research articles for free. Sci-Hub."](https://twitter.com/tdverstynen/status/1157477932098641920)

**Comment by bcardarella** [comment]
Did someone mention Sci-Hub?

**Comment by starbelly** [comment]
I am late to the party 😁 

I think it's ok to link to ACM papers. I know there's a lot of controversy and politics around all this and I can not say I am fully educated on the matter and would definitely wait for others to weigh in on this. That said, if ACM is the canonical source and possibly the only legal then it only makes sense to link to it  and does not make sense to exclude it IMO. 

 I do wonder how one would go about "liberating" this document since Joe is not around to publish it on a personal site himself - at least that's how I recall the rules being. 

And agreed from what I gathered sci-hub is 👎 
 
Perhaps we should make sure to note and be clear it's in ACM link in the link text and/or via styling.

**Comment by pdgonzalez872** [comment]
Interesting, I'm alright with the compromise of adding the link as long as we add `(Paywall)` or something to the title. The papers we currently have are direct links to pdfs. 

> "if it exists, people should be aware of it"

I agree.

Like mentioned above, we should differentiate between paywalled and direct links on the website. I don't mind appending it to the link description, along with the tags. I created https://github.com/erlef/website/issues/108 for this. Meanwhile, @bcardarella please send a PR, I'll accept.

Thanks for doing this.

**Comment by starbelly** [comment]
We never got this added. I will do so today.

**Comment by starbelly** [comment]
Done. A link is available on the site now : https://erlef.org/academic-papers/
